# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zks5tbXxaYBXtU0NKZLMmRZTBD8CeNZa
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load CSV file
file_path = 'dhinoshni.csv'
df = pd.read_csv(file_path)

# Preview data
print(df.head())

# Step 1: Vectorize genres using TF-IDF
vectorizer = TfidfVectorizer(stop_words='english')